name: Split Repos

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      repo:
        description: 'Input repo name to split, e.g. noop, open-telemetry, etc.'
        required: false
        default: ''

jobs:
  split:
    name: Split on branch ${{ github.ref }}
    if: github.repository == 'hyperf-contrib/hyperf-contrib'
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SPLIT_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Private Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Split And Push
        run: |
          git config pull.rebase true
          git config --global user.email "hyperf-contrib@flc.io"
          git config --global user.name "hyperf-contrib Developers"

          if [ -z "${{ github.event.inputs.repo }}" ]; then
            ./bin/split-linux.sh
          else
            ./bin/split-linux.sh ${{ github.event.inputs.repo }}
          fi
